foglamp/foglamp-service-notification

CMakeLists.txt
FindFogLAMP.cmake
include/notification_api.h
include/notification_service.h
notification.cpp
notification_api.cpp

FogLAMP notification serrvice: initial basic service implementation

FOGL-1997: FogLAMP notification serrvice

---

include/notification_api.h
include/notification_service.h
notification.cpp
notification_api.cpp

FOGL-2042: Add notification callback to C++ Notification service

FOGL-2042: Add notification callback to C++ Notification service

---

include/notification_manager.h
notification_manager.cpp

FOGL-2066: NotificationManager class

FOGL-2066: NotificationManager class

---

delivery_plugin.cpp
include/delivery_plugin.h

FOGL-2093: Add needed parameters to "plugin_deliver" C++ wrapper class

FOGL-2093: Add needed parameters to "plugin_deliver" C++ wrapper class

---

include/notification_manager.h
notification_manager.cpp

FOGL-1997: addition of Notification Type

FOGL-1997: addition of Notification Type

---

include/notification_queue.h
notification_queue.cpp

FOGL-2083: initial implementation of NotificationQueue

FOGL-2083: initial implementation of NotificationQueue

---

include/notification_subscription.h
notification_subscription.cpp

FOGL-2113: initial implementation of NotificationSubscription class
Note: NotificationSubscription constructor is public right now

FOGL-2113: initial implementation of NotificationSubscription class

---

include/notification_manager.h
include/overmax_rule.h
include/rule_plugin.h
notification_manager.cpp
overmax_rule.cpp
rule_plugin.cpp

FOGL-2008: addition of virtual to all RulePlugin class methods

FOGL-2008: addition of virtual to all RulePlugin class methods

---

include/notification_manager.h
include/notification_subscription.h
notification_manager.cpp
notification_subscription.cpp

FOGL-2043: addition of NotificationDetail,EvaluationType classes
When processing plugin_triggers also add each asset and its NotificationDetail to NotificationRule instance

FOGL-2043: addition of NotificationDetail,EvaluationType classes

---

include/notification_queue.h
include/notification_subscription.h
notification_queue.cpp
notification_subscription.cpp

FOGL-2161: initial implementation of notification data processing
Only Latest evaluation type is ready.
Only Notification type Retriggered is ready.
Notification send frequency not yet implemented.

FOGL-2161: WIP initial implementation of notification data processing

---

include/notification_queue.h
notification_queue.cpp

FOGL-2131: Process Notifications accordingly to RulePlugin configuration

FOGL-2131: Process Notifications accordingly to RulePlugin configuration

---

include/notification_api.h
include/notification_manager.h
notification_api.cpp
notification_manager.cpp

WIP FOGL-2173: initial implementation  of Notification API calls
Some GET methods added.
POST empty category and category register interest WIP

WIP FOGL-2173: initial implementation  of Notification API calls

---

delivery_plugin.cpp
include/delivery_plugin.h
include/notification_api.h
include/notification_manager.h
include/notification_service.h
include/overmax_rule.h
include/rule_plugin.h
notification_api.cpp
notification_manager.cpp
notification_service.cpp
overmax_rule.cpp
rule_plugin.cpp

FOGL-2173: Create an empty, disabled notification category

FOGL-2173: Create an empty, disabled notification category

---

notification_queue.cpp

FOGL-2221: deep copy readings data into rule buffers
Also fixed a Valgrind reported issue in setValue()

FOGL-2221: deep copy readings data into rule buffers

---

overmax_rule.cpp

FOGL-2262: fix compilation errors

FOGL-2262: fix compilation errors

---

include/delivery_plugin.h
include/overmax_rule.h
include/rule_plugin.h
overmax_rule.cpp
rule_plugin.cpp

FOGL-2218: addition of reconfigure to OverMax builtin rule

FOGL-2218: addition of reconfigure to OverMax builtin rule

---

rule_plugin.cpp

Reverts foglamp/foglamp-service-notification#24

Revert "FOGL-2268: Embedded rule should not call plugin manager resolveSymbol"

---

include/notification_api.h
include/notification_manager.h
notification_api.cpp
notification_manager.cpp

FOGL-2294: Addition of DELETE notification API

FOGL-2294: Addition of DELETE notification API

---

notification_manager.cpp
notification_queue.cpp

FOGL-2355: remove delete data in processDataSet()
Passed data parameter is always removed by the caller

FOGL-2355: remove delete data in processDataSet()

---

C/services/common/notification_manager.cpp

FOGL-2355: fix in loadInstances()

FOGL-2355: fix in loadInstances()

---

make_deb

FOGL-2388: fix for make_deb

---

C/services/common/include/notification_api.h
C/services/common/notification_api.cpp

FOGL-2524: URL decode category name in API calls
Note:; the decodeName() routine right now is very simple and only decodes %20

FOGL-2524: URL decode category name in API calls

---

C/services/common/overmax_rule.cpp

FOGL-2525: reduce size of displayName values.
First attempt for limiting displayName string values

FOGL-2525: reduce size of displayName values

---

C/services/notification/notification.cpp

FOGL-2301 Set default log level and add --logLevel= command line

---

C/services/common/notification_manager.cpp

Notification rule and delivery are NULL when calling addInstance

Notification rule and delivery are NULL when calling addInstance

---

C/services/common/notification_manager.cpp

FOGL-2673: add readonly to notification instance name

FOGL-2673: add readonly to notification instance name

---

C/services/common/notification_manager.cpp

and order to notificaiton category

FOGL-2645 Remove prepending of Notification to name. Add displayNames

---

C/services/common/include/notification_api.h
C/services/common/notification_api.cpp
C/services/common/notification_manager.cpp

FOGL-2685: handle special characters in instance/rule/delivery name
A name with double quotes does not work.
it will be fixed with another JIRA task

FOGL-2685: handle special characters in instance/rule/delivery name

---

C/services/common/include/notification_subscription.h
C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp
C/services/common/notification_subscription.cpp

FOGL-2721: fix crash for enable/disable notifications
Tested on Ubuntu 18, Ubuntu 16 and Pi3 with Valgrind

FOGL-2721: fix crash for enable/disable notifications

---

C/services/common/delivery_plugin.cpp
C/services/common/include/delivery_plugin.h
C/services/common/notification_queue.cpp

FOGL-2688: Enable flag in notification delivery plugin

FOGL-2688: Enable flag in notification delivery plugin

---

C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp

FOGL-2699: Allow notitification instace name with double quotes

FOGL-2699: Allow notitification instace name with double quotes

---

Description
Package
make_rpm
packages/RPM/SPECS/service.spec

FOGL-2822: RPM packaging for Notification server

FOGL-2822: RPM packaging for Notification server

---

C/services/common/include/notification_manager.h
C/services/common/notification_manager.cpp
tests/unit/C/services/notification/check_notification_state.cpp

FOGL-2848: Fix notification service notification type
Fix for TOGGLED and ONE SHOT

FOGL-2848: Fix notification service notification type

---

C/services/common/include/notification_manager.h
C/services/common/notification_manager.cpp
tests/unit/C/services/notification/check_notification_state.cpp

FOGL-2854: Make notification re-trigger time user configurable

FOGL-2854: Make notification re-trigger time user configurable

---

tests/unit/C/services/notification/api_url.cpp
tests/unit/C/services/notification/check_notification_state.cpp
tests/unit/C/services/notification/get_instances.cpp
tests/unit/C/services/notification/get_plugins.cpp
tests/unit/C/services/notification/main.cpp
tests/unit/C/services/notification/queue.cpp
tests/unit/C/services/notification/remove_instance.cpp

FOGL-2884: Trap unexpected failures Notification Server C++ unit tests

FOGL-2884: Trap unexpected failures Notification Server C++ unit tests

---

tests/unit/C/services/notification/api_url.cpp
tests/unit/C/services/notification/check_notification_state.cpp
tests/unit/C/services/notification/get_instances.cpp
tests/unit/C/services/notification/get_plugins.cpp
tests/unit/C/services/notification/queue.cpp
tests/unit/C/services/notification/remove_instance.cpp

Remove ASSERT_* in unit tests

---

build.sh
build_deb.sh
build_rhel.sh
make_rpm
requirements.sh

FOGL-2924: Segmentation fault while installing foglamp-service-notification package on rhel/centos

FOGL-2924: Segmentation fault while RPM package on rhel/centos

---

C/services/common/include/notification_manager.h
C/services/common/include/notification_queue.h
C/services/common/notification_queue.cpp
C/services/common/notification_subscription.cpp
C/services/common/threshold_rule.cpp

FOGL-2979: Rules config change
Changes in Notification service core and in embedded rule.
Notitication rule plugins will be modified in their own repositories

FOGL-2979: Rules config change

---

C/services/common/notification_queue.cpp

FOGL-3121: Check delivery plugin in Notification server evalRule

FOGL-3121: Check delivery plugin in Notification server evalRule

---

C/services/common/threshold_rule.cpp

FOGL-3171 Update the plugin description and hide the Rule configuration

---

C/services/common/threshold_rule.cpp

FOGL-3171 Update the plugin description and hide the Rule configuration [1.7.0 RC]

---

C/services/common/include/notification_manager.h
C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp

FOGL-3181: fix reconfiguration / enable / disable crash
Initial implementation

FOGL-3181: fix reconfiguration / enable / disable crash

---

C/services/common/notification_manager.cpp

Mark instances as zombie before deleting them

Mark instances as zombie before deleting them

---

C/services/common/include/notification_manager.h
C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp
C/services/common/notification_subscription.cpp

Update notification_subscription.cpp
#93 by pintomax
Update notification_manager.cpp
#92 by pintomax 
Mark instances as zombie before deleting them
#91 by pintomax 
FOGL-3181: fix reconfiguration / enable / disable crash
#90 by pintomax

FOGL-3181  [1.7.0 rc]

---

C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp
C/services/common/notification_service.cpp
C/services/common/notification_subscription.cpp

FOGL-3181: Fixes for instance removal

FOGL-3181: Fixes for instance removal

---

C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp
C/services/common/notification_service.cpp
C/services/common/notification_subscription.cpp

FOGL-3181: Fixes for instance removal
This PR is cherry-pick of #95 ;

FOGL-3181 (2) Fixes for instance removal [1.7.0 rc]

---

C/services/common/notification_queue.cpp
C/services/common/notification_subscription.cpp

Fix for instance enable/disable

Fix for instance enable/disable

---

C/services/common/notification_queue.cpp
C/services/common/notification_subscription.cpp

Fix for instance enable/disable (1.7.0 RC) 

---

C/services/common/include/notification_manager.h
C/services/common/notification_manager.cpp
C/services/common/notification_queue.cpp

FOGL-3184: addition of autit entry NTCLR

FOGL-3184: addition of autit entry NTCLR

---

C/services/common/notification_manager.cpp

Change audit notification key for Cleared

Change audit notification key for Cleared

---

C/services/common/include/notification_queue.h
C/services/common/notification_queue.cpp

FOGL-3204 Delays in sending notifications  (1.7.0 RC)
